# Generated by Django 3.1.7 on 2021-05-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user_id',
        ),
    ]
