# Generated by Django 3.1.7 on 2021-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_remove_wallet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
