# Generated by Django 3.1.7 on 2021-05-12 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0004_wallet_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
