# Generated by Django 3.1.7 on 2021-05-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0005_auto_20210512_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=50),
        ),
    ]
