# Generated by Django 3.1.7 on 2021-05-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0007_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='transaction',
            new_name='tc',
        ),
    ]
