# Generated by Django 3.1.7 on 2021-05-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0008_auto_20210513_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
