# Generated by Django 3.1.7 on 2021-05-13 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0012_auto_20210513_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans_log',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
